min_version = "2026.9.17"

[tools]
go = "1.27.1"
node = "26.10.0"
uv = "0.12.22"

[tools."http:vscode"]
version = "latest"
version_list_url = "https://update.code.visualstudio.com/api/update/linux-{{ arch() }}/stable/latest"
version_json_path = ".productVersion"
url = "https://update.code.visualstudio.com/{{ version }}/linux-{{ arch() }}/stable"
checksum_url = "https://update.code.visualstudio.com/api/update/linux-{{ arch() }}/stable/latest"
checksum_expr = '"sha256:" + fromJSON(body).sha256hash'
format = "tar.gz"
strip_components = 1
bin_path = "bin"

[env]
_.path = ["{{env.HOME}}/.go/bin"]
GOPATH = "{{env.HOME}}/.go"
GOPROXY = "https://goproxy.cn,direct"
UV_DEFAULT_INDEX = "https://mirrors.aliyun.com/pypi/simple/"

[settings]
lockfile = true
